name: Continuous Delivery

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'

env:
  repository: Fresa/TestContainers.Xunit.Reusable
  project_path: src/TestContainers.Xunit
  project_name: TestContainers.Xunit
  dotnet_version: 9.0.x
  
jobs:
  test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        id: dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet_version }}
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
    outputs:
      dotnet_version: ${{ steps.dotnet.outputs.dotnet-version }}
      repository: ${{ env.repository }}
      project_path: ${{ env.project_path }}
      project_name: ${{ env.project_name }}

  release:
    name: Create Release
    uses: Fresa/Library.Net.ContinuousDelivery/.github/workflows/release.yml@v0
    needs: test
    if: github.repository == needs.test.outputs.repository && github.actor != 'dependabot[bot]'
    permissions: 
      contents: write
    with:
      project_path: ${{ needs.test.outputs.project_path }}
      project_name: ${{ needs.test.outputs.project_name }}
      dotnet_version: ${{ needs.test.outputs.dotnet_version }}
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
